name: Sincronizar Fotos desde Drive

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "10 21 * * 6" #Todos los sabados a las 9:10 PM hora local (colombia)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r github_actions_requirements.txt

      - name: Correr script de descarga
        run: python sync_images.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: "6543"
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          FOTOS_FOLDER_ID: ${{ secrets.FOTOS_FOLDER_ID }}

      - name: Subir cambios al repositorio
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add static/images/events/
          git add static/images/fotos/

          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto: Sincronización de imágenes (eventos y fotos)"
            git push
          else
            echo "No se detectaron archivos nuevos."
          fi
